### ISSUE TITLE
Jewel Purposer casing lag

### ISSUE THREAD

**Issue by mrGRINCH** [ImplementsLegend/VaultJewelPurposer#4]
The jewel purposer uses a LOT of MSPT. (see image below)

I only have 200 jewels inside of it in the screenshot and it's using 2530 MSPT.

https://egirl.rip/6TLKSio9pC.png?key=p4Ft7odiKygRZh

**Comment by ImplementsLegend** [comment]
I never said that it's a light mod and 2.5 milliseconds isn't that bad, btw is it client lag or server lag?

**Comment by mrGRINCH** [comment]
Oh you're right, it's showing microseconds not milliseconds so only 2.5ms which isn't too bad.
 
It seemed to be server lag at the time but I will try and do some more testing.

**Comment by mrGRINCH** [comment]
I believe I was mistaken in the lag source and it's not your mod that was causing it, apologise.
